/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentGuideRouteImport } from './routes/agent-guide'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardCuidRouteRouteImport } from './routes/dashboard/$cuid/route'
import { Route as DashboardCuidIndexRouteImport } from './routes/dashboard/$cuid/index'
import { Route as DashboardCuidPortfolioRouteImport } from './routes/dashboard/$cuid/portfolio'
import { Route as DashboardCuidOrdersRouteImport } from './routes/dashboard/$cuid/orders'
import { Route as DashboardCuidMarketRouteImport } from './routes/dashboard/$cuid/market'

const AgentGuideRoute = AgentGuideRouteImport.update({
  id: '/agent-guide',
  path: '/agent-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCuidRouteRoute = DashboardCuidRouteRouteImport.update({
  id: '/dashboard/$cuid',
  path: '/dashboard/$cuid',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCuidIndexRoute = DashboardCuidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCuidRouteRoute,
} as any)
const DashboardCuidPortfolioRoute = DashboardCuidPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardCuidRouteRoute,
} as any)
const DashboardCuidOrdersRoute = DashboardCuidOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardCuidRouteRoute,
} as any)
const DashboardCuidMarketRoute = DashboardCuidMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashboardCuidRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-guide': typeof AgentGuideRoute
  '/dashboard/$cuid': typeof DashboardCuidRouteRouteWithChildren
  '/dashboard/$cuid/market': typeof DashboardCuidMarketRoute
  '/dashboard/$cuid/orders': typeof DashboardCuidOrdersRoute
  '/dashboard/$cuid/portfolio': typeof DashboardCuidPortfolioRoute
  '/dashboard/$cuid/': typeof DashboardCuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-guide': typeof AgentGuideRoute
  '/dashboard/$cuid/market': typeof DashboardCuidMarketRoute
  '/dashboard/$cuid/orders': typeof DashboardCuidOrdersRoute
  '/dashboard/$cuid/portfolio': typeof DashboardCuidPortfolioRoute
  '/dashboard/$cuid': typeof DashboardCuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-guide': typeof AgentGuideRoute
  '/dashboard/$cuid': typeof DashboardCuidRouteRouteWithChildren
  '/dashboard/$cuid/market': typeof DashboardCuidMarketRoute
  '/dashboard/$cuid/orders': typeof DashboardCuidOrdersRoute
  '/dashboard/$cuid/portfolio': typeof DashboardCuidPortfolioRoute
  '/dashboard/$cuid/': typeof DashboardCuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-guide'
    | '/dashboard/$cuid'
    | '/dashboard/$cuid/market'
    | '/dashboard/$cuid/orders'
    | '/dashboard/$cuid/portfolio'
    | '/dashboard/$cuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-guide'
    | '/dashboard/$cuid/market'
    | '/dashboard/$cuid/orders'
    | '/dashboard/$cuid/portfolio'
    | '/dashboard/$cuid'
  id:
    | '__root__'
    | '/'
    | '/agent-guide'
    | '/dashboard/$cuid'
    | '/dashboard/$cuid/market'
    | '/dashboard/$cuid/orders'
    | '/dashboard/$cuid/portfolio'
    | '/dashboard/$cuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentGuideRoute: typeof AgentGuideRoute
  DashboardCuidRouteRoute: typeof DashboardCuidRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agent-guide': {
      id: '/agent-guide'
      path: '/agent-guide'
      fullPath: '/agent-guide'
      preLoaderRoute: typeof AgentGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$cuid': {
      id: '/dashboard/$cuid'
      path: '/dashboard/$cuid'
      fullPath: '/dashboard/$cuid'
      preLoaderRoute: typeof DashboardCuidRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$cuid/': {
      id: '/dashboard/$cuid/'
      path: '/'
      fullPath: '/dashboard/$cuid/'
      preLoaderRoute: typeof DashboardCuidIndexRouteImport
      parentRoute: typeof DashboardCuidRouteRoute
    }
    '/dashboard/$cuid/portfolio': {
      id: '/dashboard/$cuid/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/$cuid/portfolio'
      preLoaderRoute: typeof DashboardCuidPortfolioRouteImport
      parentRoute: typeof DashboardCuidRouteRoute
    }
    '/dashboard/$cuid/orders': {
      id: '/dashboard/$cuid/orders'
      path: '/orders'
      fullPath: '/dashboard/$cuid/orders'
      preLoaderRoute: typeof DashboardCuidOrdersRouteImport
      parentRoute: typeof DashboardCuidRouteRoute
    }
    '/dashboard/$cuid/market': {
      id: '/dashboard/$cuid/market'
      path: '/market'
      fullPath: '/dashboard/$cuid/market'
      preLoaderRoute: typeof DashboardCuidMarketRouteImport
      parentRoute: typeof DashboardCuidRouteRoute
    }
  }
}

interface DashboardCuidRouteRouteChildren {
  DashboardCuidMarketRoute: typeof DashboardCuidMarketRoute
  DashboardCuidOrdersRoute: typeof DashboardCuidOrdersRoute
  DashboardCuidPortfolioRoute: typeof DashboardCuidPortfolioRoute
  DashboardCuidIndexRoute: typeof DashboardCuidIndexRoute
}

const DashboardCuidRouteRouteChildren: DashboardCuidRouteRouteChildren = {
  DashboardCuidMarketRoute: DashboardCuidMarketRoute,
  DashboardCuidOrdersRoute: DashboardCuidOrdersRoute,
  DashboardCuidPortfolioRoute: DashboardCuidPortfolioRoute,
  DashboardCuidIndexRoute: DashboardCuidIndexRoute,
}

const DashboardCuidRouteRouteWithChildren =
  DashboardCuidRouteRoute._addFileChildren(DashboardCuidRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentGuideRoute: AgentGuideRoute,
  DashboardCuidRouteRoute: DashboardCuidRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
